name: DynamicRegions
main: net.projectzombie.dynamic_regions.main.Main
version: 1.0
depend: [WorldEdit,WorldGuard,MythicMobs]
commands:
  bw:
    description: Memory used storing blocks.
    usage: "Usage: /bw lore"
  gunsmith:
    description: Access the gunsmith at spawn to modify weapons.
    usage: "/gunsmith"
  gs:
    description: Access the gunsmith at spawn to modify weapons.
    usage: "/gs"
