name: CustomInteractions
main: net.projectzombie.custom_interactions.main.Main
depend: [WorldEdit,WorldGuard]
version: 1.0
commands:
  bp:
    description: Nope.
    usage: "WIP"
  engrave:
    description: Nope.
    usage: "WIP"
