name: CrackShotEnhanced
main: net.projectzombie.crackshot_enhanced.main.Main
version: 1.0
depend: [CrackShot]
commands:
  bw:
    description: Memory used storing blocks.
    usage: "Usage: /bw entries, /bw restore"
